### ISSUE TITLE
Reduce the number of lines of code to < 100 lines in `json.js`

### ISSUE THREAD

**Issue by Fawke** [pramithprakash/reactTrainingExe#10]
Write the filtration logic in a function. So there should be two separate functions, one of filtering theft.json data and one for assault.json data.

**Comment by pramithprakash** [comment]
Hi, I have done and pushed the above mentioned changes

**Comment by pramithprakash** [comment]
Moved a seperate repo- https://github.com/pramithprakash/data-munging-assignment
